---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    samson/prerequisite: "true"
  name: data-migration
  labels:
    project: project
    role: data-migration
spec:
  template:
    metadata:
      labels:
        project: project
        role: data-migration
    spec:
      restartPolicy: Never
      containers:
      - name: project-data-migration
        image: 655555973700.dkr.ecr.us-east-1.amazonaws.com/project:latest
        command: ["sh", "-c", "sleep 10; /bin/data_migration.bash"]
